### ISSUE TITLE
Error with static template block tag in Django 1.3

### ISSUE THREAD

**Issue by msmenzyk** [allink/django-admin-import#3]
Old import_xls.html cause Error with static template block tag in Django 1.3

{% extends "admin/base_site.html" %}
{% load i18n static %}

... 
href="{% static "admin/css/forms.css" %}" />
...

This is OK: (https://docs.djangoproject.com/en/1.3/howto/static-files/#with-a-template-tag)

{% extends "admin/base_site.html" %}
{% load i18n static %}
{% get_static_prefix as STATIC_PREFIX %}

...
href="{{ STATIC_PREFIX }}admin/css/forms.css" />
...

**Comment by frog32** [comment]
this has been fixed in 60f32026db9825403da40057c3fbca0d4025ef06 and is in relese 0.3.0
